export const ActionTypes={
    SET_PRODUCT:"SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    FETCH_DATA_REQUEST: " FETCH_DATA_REQUEST",
    FETCH_DATA_FAILURE:" FETCH_DATA_FAILURE",
}